created example api/routes [MB-3] [MB-4] [MB-5]
Codubee/MathSkillsMW5-6-Back pull request #5
Opened 2021-08-02 22:40 UTC by khreate

* **Please check if the PR fulfills these requirements**
- [✅] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
This PR creates three new features in a new API that interfaces with the people example API.
These features are routes to get all of the people in the API, remove a person from the API, and add a person to the API.

* **What is the current behavior?What does the code do before you made the new changes?** 
Previous to these changes, the code did nothing (index.js empty)

* **What is the new behavior?**
This code when executed will run an API.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
This PR requires the user to run the api start command from their terminal.

2021-08-05 21:27 UTC, Codubee requested changes
Left a comment

2021-08-05 21:27 UTC, Codubee commented on SK/index.js
> +    axios.post("http://java-sample-api-2020.herokuapp.com/addPerson", bodyPost) // POST request attempted here
The post did not work here. Might have to try this one out and see if it works.

2021-08-11 22:03 UTC, khreate reviewed
Fixed a variable name error, should be working now

2021-08-11 22:23 UTC, Codubee approved these changes
LGTM!

2021-08-11 22:23 UTC, merged